#import the python libraries needed
import RPi.GPIO as GPIO #import library RPi.GPIO & calling it GPIO
import time             #import time library to call time.sleep (delay)

#set the GPIO mode to Broadcom pin
GPIO.setmode(GPIO.BCM) #Broadcom(BCM) use to configure Raspberry Pi pins using the Broadcom channel num.

GPIO.setwarnings(False)#Suppresse any warnings generated by RPi.GPIO library

#set the pins and if its an output or input
Button = 20                                          #assign GPIO pin number 20 as Button
LED = 21                                             #assign GPIO pin number 21 as LED
Motor = 19                                           #assign GPIO pin number 19 as Motor (Relay module)
GPIO.setup(Button,GPIO.IN, pull_up_down=GPIO.PUD_UP) #set the Button GPIO pin as an input
GPIO.setup(Motor, GPIO.OUT)                          #set the Motor GPIO pin as an Output
GPIO.setup(LED,GPIO.OUT)                             #set the LED GPIO pin as an Output

#---------Coding situation: When button is pressed Motor & LED turns on. When button is not pressed the Motor & LED will remain off ---------
while True:
    Btn = GPIO.input(20)        #resigning pin 20 as Btn
    
    if Btn == False:            #when btn is pressed {checking: if the button is being pushed}
        GPIO.output(Motor, True)#Turn on the Motor
        GPIO.output(LED, True)  #Turn on the LED
        print ("Motor on")      #print "Motor on" in the terminal
        time.sleep (2)          #wait for 2 seconds

    else:
        GPIO.output(Motor, False)#Turn off the Motor
        GPIO.output(LED,False)   #Turn off the LED
        print ("Motor off")      #print "Motor off" in the terminal
        time.sleep(3)            #wait for 3 seconds

#Clean up GPIO and release resources
GPIO.cleanup #clean up 