#import the python libraries needed
import RPi.GPIO as GPIO                        #import library RPi.GPIO & calling it GPIO
import time as delay                           #need to import time as delay. As time has already been imported in line 5
import schedule                                #library need to be downloaded & raspberry time need to be set
from datetime import time, timedelta, datetime #time -> specify a time, timedelta ->specifying time difference & datetime -> specifying a date and time


#set the GPIO mode to Broadcom pin
GPIO.setmode(GPIO.BCM) #Broadcom(BCM) use to configure Raspberry Pi pins using the Broadcom channel num.
GPIO.setwarnings(False)#Suppresse any warnings generated by RPi.GPIO library

def medication():                #defining a funtion called "medication"
    print ("time for medication")#print "time for medication " on the terminal 

schedule.every(3).seconds.do(medication) #scheduling a task ".do(medication)" will run every 3Seconds

#---------Coding situation: When pushbutton is pressed LED turn on. N When pushbutton is not pressed LED turn off ---------
while True:
    schedule.run_pending()  #check and excute any pending schedule task that is due to run
    delay.sleep(2)          # wait for 2 seconds       

#Clean up GPIO and release resources
GPIO.cleanup()#Clean up